<?php
// Language variables
$template->assign_vars(array(
    'L_BASE64'			    => 'Base 64',
    'L_BACKTOTOP'			=> 'Back to top',
    'L_BINARY'              => 'Binary',
    'L_CHECKF'              => 'Check Files',
    'L_CHECK_FILES'         => 'Upload a file to examine its file type / header',
    'L_CHECK_EXP'           => 'Only the first 32 bytes of each file is read and then discarded. No uploaded files are actually stored anywhere on this server.',
    'L_DECODE'				=> 'Decode',
    'L_DEC'                 => 'Dec / Char',
    'L_DEF_DELIMITER_DASH'  => 'Default is a dash',
    'L_DEF_DELIMITER_SPACE' => 'Default is a space',
    'L_DEF_DELIMITER_EMPTY' => 'Default is empty',
    'L_DELIMITER'			=> 'Delimiter',
    'L_DOWNLOAD'			=> 'Download',
    'L_ENCODE'				=> 'Encode',
    'L_EXPLODE_STRING'      => 'explode on string',
    'L_FILEH'               => 'File Headers',
    'L_FILEH_COMMON'        => 'A list of common file headers (HEX format)',
    'L_FILE_NAME'			=> 'File Name',
    'L_FOOTER'              => 'Footer',
	'L_HASH' 				=> 'Hash',
	'L_HEX'    				=> 'Hex',
	'L_HEX_ANALYSE'         => 'Analyse hex frequencies and patterns',
	'L_HEXP'    			=> 'Hex Patterns',
	'L_HIDE'				=> 'Hide',
	'L_HOME'				=> 'Home',
    'L_MD5'					=> 'MD5',
    'L_MORSE'              	=> 'Morse',
    'L_MORSENARY'       	=> 'Morsenary (. = 0, - = 1)',
    'L_OFF'                 => 'Off',
    'L_ON'                  => 'On',
    'L_RESULTS'             => 'Results',
    'L_REVERSE'             => 'Reverse',
    'L_RUN'                 => 'Run',
    'L_SELECT_TEXT'			=> 'Select text',
    'L_SIZE'				=> 'Size',
    'L_SHOW'				=> 'Show',
	'L_SUBMIT'				=> 'Submit',
	'L_TEXT'				=> 'Text',
	'L_TOGGLE_CASE'         => 'Case Sensitivity',
	'L_URL_ENC'             => 'URL Encoded',
    'L_WORD_ANALYSE'        => 'Analyse word &amp; character counts and frequencies',
    'L_WORDF'               => 'Word Freqs',
    'L_WORDS'               => 'Word Counter / Frequencies',
    
    'L_BMP'                 => 'BMP',
    'L_DOC'                 => 'Office Application Document',
    'L_GIF'                 => 'Gif',
    'L_GIF_87A'             => '(87a)',
    'L_GIF_89A'             => '(89a)',
    'L_MID'                 => 'Midi',
    'L_MP3'                 => 'MP3 (ID3)',
    'L_MP4'                 => 'MP4',
    'L_MPEG4_V1'            => '(MPEG-4 v1)',
    'L_MPEG4_V2'            => '(MPEG-4 v2)',
    'L_PDF'                 => 'PDF',
    'L_PNG'                 => 'PNG',
    'L_PSD'                 => 'PSD (Photoshop)',
    'L_WAV'                 => 'Wav/Audio',
    'L_ZIP'                 => 'Zip/Compressed',
    
    'L_BYTES_BMP'           => '42 4D',
    'L_BYTES_DOC'           => 'D0 CF 11 E0   A1 B1 1A E1',
    'L_BYTES_GIF87'         => '47 49 46 38   37 61',
    'L_BYTES_GIF89'         => '47 49 46 38   39 61',
    'L_BYTES_MID'           => '4D 54 68 64   00 00 00 06',
    'L_BYTES_MP3'           => '49 44 33 03',
    'L_BYTES_MP4_V1'        => '66 74 79 70   69 73 6F 6D',
    'L_BYTES_MP4_V2'        => '66 74 79 70   6D 70 34 32',
    'L_BYTES_PDF'           => '25 50 44 46',
    'L_BYTES_PNG'           => '89 50 4E 47   0D 0A 1A 0A   00 00 00 0D   49 48 44 52',
    'L_BYTESF_PNG'          => '49 45 4E 44   AE 42 60 82',
    'L_BYTES_PSD'           => '38 42 50 53   00 01',
    'L_BYTES_WAV'           => '52 49 46 46   XX XX XX XX   57 41 56 45',
    'L_BYTES_ZIP'           => '50 4B 03 04',

));