<?php
// Language variables
$template->assign_vars(array(
    'L_BASE64'			    => 'Base 64',
    'L_BACKTOTOP'			=> 'Back to top',
    'L_BINARY'              => 'Binary',
    'L_DECODE'				=> 'Decode',
    'L_DEC'                 => 'Dec / Char',
    'L_DOWNLOAD'			=> 'Download',
    'L_ENCODE'				=> 'Encode',
    'L_FILE_NAME'			=> 'File Name',
	'L_HASH' 				=> 'Hash',
	'L_HEX'    				=> 'Hex',
	'L_HIDE'				=> 'Hide',
	'L_HOME'				=> 'Home',
    'L_MD5'					=> 'MD5',
    'L_MORSE'              	=> 'Morse',
    'L_MORSENARY'       	=> 'Morsenary (. = 0, - = 1)',
    'L_REVERSE'             => 'Reverse',
    'L_SELECT_TEXT'			=> 'Select text',
    'L_SIZE'				=> 'Size',
    'L_SHOW'				=> 'Show',
	'L_SUBMIT'				=> 'Submit',
	'L_TEXT'				=> 'Text',
	'L_URL_ENC'             => 'URL Encoded',
    'L_WORDF'               => 'Word Freqs',
    'L_WORDS'               => 'Word Counter / Frequencies',
));